module.exports = {
    statuses: {
        '406': 'Invalid Content Type Error',
        '420': 'Validation Error',
        '421': 'Reserved for customs',
        '422': 'Invalid Verification Pin',
        '423': 'Pin Expired',
        '424': 'Phone number not verifiable',
        '425': 'Phone Number not Editable Error',
        '426': 'Phone Number already Verified Error',
        '434': 'Invalid Transaction Error',
        '442': 'Wallet Share limit exceeded error',
        '445': 'Cant find contacts on server. Reupload please!!',
        '451': 'Invalid Phone Number Error',
        '455': 'Phone Number already verified',
        '457': 'Phone Number count Full',
        '465': 'Invalid Login Details',
        '468': 'Phone number not accessible by user',
        '469': 'Phone number count not greater than 1',
        '474': 'Already Exists',
        '475': 'User already Exists',
        '480': 'User not found Error',
        '482': 'User Devices Not Found',
        '490': 'Authentication Error',
        '492': 'Not your Device Error',
        '495': 'Device not activated',
        '497': 'Maintenance Mode',
        '499': 'User not Active',
        '444': 'Already Accepted'
    }
};
